sudo: required

services:
  - docker

before_install:
- docker pull jekyll/jekyll
- docker pull attensee/s3_website

language: ruby
rvm:
  - 2.2
install: gem install jekyll -v 3.2.1 && gem install s3_website && gem install minima
script: jekyll build

deploy:
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do s3_website push --force
  skip_cleanup: true
  on:
    branch: master

